[updates]
strategy = "periodic"

[updates.periodic]
time_zone = "localtime"

[[updates.periodic.window]]
days = [ "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" ]
start_time = "3:00"
length_minutes = 60